rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  ignore-url: /film/beforeAddFilm,/film/films,/admin/login,/user/register,/user/check,/film/getIndex,/film/getConditionList,/film/getFilms,/cinema/getFields,/cinema/getCondition,/cinema/getCinemas,/cinema/getFieldInfo,/cinema/getCinemaInfo,/film/list5HotSearch #忽略列表
server:
  port: 80 #项目端口

mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/rest/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.rest.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
#springbootadmin监控注册中心
  boot:
      admin:
        client:
          url: http://localhost:9110
  application:
      name: meeting-gateway
  dubbo:
      server: true
      registry: zookeeper://localhost:2181
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/guns_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: yourpassword
      filters: log4j,wall,mergeStat
  rabbitmq:
        addresses: 106.14.113.7:5672
        username: guest
        password: guest
        virtual-host: /
        connection-timeout: 15000
        #实现一个监听器用于监听Broker端给我们返回的确认请求
        publisher-confirms: true
        #保证消息对broker端是可达的，如果出现路由键不可达的情况，则使用监听器对不可达的消息进行后续处理，保证消息的路由成功
        publisher-returns: true
        #在发送消息的时候对template进行配置mandatory=ture保证监听有效
        template:
            mandatory: true

#Redis
redis:
  hostname: gongyu91.cn
  port: 6379
  password: yourpassword
  pool:
      maxActive: 5000
      maxIdle: 20
      maxWait: 3000
      testOnBorrow: true
      timeOut: 3000


logging:
  level.root: info
  level.com.stylefeng: debug
  file: /root/meetingfilm/log/gateway.log