rest:
  auth-open: false #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)

#Redis
redis:
  hostname: gongyu91.cn
  port: 6379
  password: yourpassword
  pool:
      maxActive: 5000
      maxIdle: 20
      maxWait: 3000
      testOnBorrow: true
      timeOut: 3000


jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
ftp:
  host-name: "106.14.113.7"
  port: 21
  user-name: "gongyu"
  password: "yourpassword"
server:
  port: 8086 #项目端口

mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/rest/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.rest.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用


management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  boot:
    admin:
      client:
        url: http://localhost:9110
  application:
      name: meeting-order
  dubbo:
      server: true
      registry: zookeeper://localhost:2181
      protocol:
         name: dubbo
         port: 20886
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/guns_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: yourpassword
      filters: log4j,wall,mergeStat
  rabbitmq:
      addresses: 106.14.113.7:5672
      username: guest
      password: guest
      virtual-host: /
      connection-timeout: 15000
      listener:
          simple:
              acknowledge-mode: manual
              concurrency: 5
              max-concurrency: 10
          order-overtime:
              queue:
                  name: order_id-overtime-dead
                  durable: true
              exchange:
                  name: order_id_dead
                  durable: true
                  type: direct
                  ignoreDeclarationExceptions: true
              key: order_id.overtime.dead
          order:
              queue:
                  name: order_id-overtime
                  durable: true
              exchange:
                  name: order_id
                  durable: true
                  type: direct
                  ignoreDeclarationExceptions: true
              key: order_id.overtime



logging:
  level.root: info
  level.com.stylefeng: debug
  file: /root/meetingfilm/log/order.log